"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['mugic_display.py']
DATA_FILES = []
OPTIONS = {}

setup(
    app=APP,
    argv_emulation=True,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
