"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import glob

APP = ['mugical_ball.py']
DATA_FILES = [('assets', glob.glob('assets/*'))]
OPTIONS = {}

setup(
    app=APP,
    argv_emulation=True,
    package='quaternion',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
